meta:
  engine: 4.1.0
  name: boost58
  version: 0.1
  ref: &kb_ref ""
  author: Vacant0mens
  footprint: &switch_footprint "ceoloide/switch_choc_v1_v2"
  switch:
    $extends: presets.choc
presets:
  choc:
    # Key and keycap measures
    kx: cx # spacing between key centers (X-axis)
    ky: cy # spacing between key centers (Y-axis)
    key_spread: 20 # horizontal space between columns (default: 19)
    key_padding: 19 # vertical padding between keys (deafult: 19)
    keycap_w: 17.5 # keycap width (cherry: 18, choc: 17.5)
    keycap_h: 16.5 # keycap height (cherry: 18, choc: 16.5)
    key_cutout_w: 13.8 # key cutout hole width (cherry, choc v2: 14, choc v1: 13.8)
    key_cutout_h: 13.8 # key cutout hole height (cherry, choc v2: 14, choc v1: 13.8)
    led_pos_x: 0 # Led X position relative to the switch center
    led_pos_y: 5 # Led Y position relative to the switch center
    led_rotation: 0 # Led rotation
    diode_pos_x: -8 # diode Y position relative to switch center
    diode_pos_y: 2 # diode Y position relative to switch center
    diode_rotation: -90 # Diode rotation
    switch_rotation: 180 # Hotswap south, led north
    screw_hole_radius: 1.6 # M3 hole; 1.6 x 2 = diameter: 3.2
    heat_insert_hole_radius: 2.4 # 2.4mm x 2 = 4.8mm (threaded inserts are 5mm)
    screw_material_radius: 3.2 # 3.2 x 2 = 6.4 diameter -- three wall lines of 0.4mm
    mx_kx: u # spacing between key centers (X-axis)
    mx_ky: u # spacing between key centers (Y-axis)
    mx_key_spread: 19 # horizontal space between columns (default: 19)
    mx_key_padding: 19 # vertical padding between keys (deafult: 19)
    mx_key_cutout_w: 14 # key cutout hole width (cherry: 14, choc: 13.8)
    mx_key_cutout_h: 14 # key cutout hole height (cherry: 14, choc: 13.8)
    mx_keycap_w: 18 # keycap width (cherry: 18, choc: 17.5)
    mx_keycap_h: 18 # keycap height (cherry: 18, choc: 16.5)
    mx_led_pos_x: 0 # Led X position relative to the switch center
    mx_led_pos_y: -4.75 # Led Y position relative to the switch center
    mx_led_rotation: 0 # Led rotation
    mx_diode_pos_y: 2 # How much to shift to avoid overlap
    mx_diode_pos_x: -8
    mx_diode_rotation: -90 # Diode rotation
    mx_switch_rotation: 180 # Hotswap north, led south
units:
  $extends: meta.switch
points:
  zones:
    matrix:
      anchor:
        shift: [40, -120]
      key:
        tags:
        - key
        spread: key_spread
        padding: key_padding
        bind: [2, 2, 2, 2]
      rows:
        bottom:
          row_net: D5
          led_row: 1
          led_row_next: 1
        home:
          row_net: D4
          led_row: 2
          led_row_next: 2
        top:
          row_net: D3
          led_row: 3
          led_row_next: 3
        num:
          row_net: D2
          led_row: 4
          led_row_next: 4
      columns:
        outer:
          key:
            bind: [2, 2, 4, 4]
            led_col: '0'
            led_col_next: 1
            column_net: D29
        pinky:
          key:
            led_col: 1
            led_col_next: 2
            column_net: D28
            stagger: 10
        ring:
          key:
            led_col: 2
            led_col_next: 3
            column_net: D27
            stagger: 12
        middle:
          key:
            led_col: 3
            led_col_next: 4
            column_net: D26
            stagger: 4
        index:
          key:
            led_col: 4
            led_col_next: 5
            stagger: -4
            column_net: D22
        inner:
          key:
            led_col: 5
            led_col_next: '0'
            stagger: -6
            column_net: D20
          rows:
            bottom:
              bind: [2, 10, 8, 2]
              led_row_next: '2'
            home:
              bind: [2, 26, 10, 2]
              led_row_next: '3'
            top:
              bind: [4, 26, 2, 2]
              led_row_next: '4'
            num:
              bind: [4, 26, 2, 2]
              led_row_next: ''
              led_col_next: ''
    thumb:
      anchor:
        ref: matrix_inner_bottom
        shift: [-60, -16]
      key:
        tags:
        - key
        led_row: '0'
        led_row_next: '0'
        spread: key_spread
        row_net: D6
      rows:
        only:
          padding: key_padding
      columns:
        first:
          key:
            column_net: D29
            led_col: 1
            led_col_next: 2
          rows:
            only:
              bind: [6, 2, 4, 22]
        second:
          key:
            column_net: D28
            led_col: 2
            led_col_next: 3
          rows:
            only:
              bind: [8, 4, 4, 2]
        third:
          key:
            led_col: 3
            led_col_next: 4
            stagger: -1
            splay: -5
            column_net: D27
          rows:
            only:
              bind: [8, 4, 4, 4]
        home:
          key:
            led_col: 4
            led_col_next: 5
            spread: 19
            splay: -15
            origin: [-9, -9.5]
            column_net: D26
          rows:
            only:
              bind: [4, 4, 4, 4]
        inner:
          key:
            led_col: 5
            led_col_next: '0'
            spread: 18
            splay: -20
            origin: [-9, -9.5]
            column_net: D22
          rows:
            only:
              bind: [4, 4, 4, 8]
              led_row_next: 1
    screw_outer_bottom:
      key:
        tags:
        - screw
      anchor:
        ref: matrix_outer_bottom
        shift: [11, 0]
    screw_outer_top:
      $extends: points.zones.screw_outer_bottom
      anchor:
        ref: matrix_outer_num
        shift: [11, 0]
    screw_middle_bottom:
      $extends: points.zones.screw_outer_bottom
      anchor:
        ref: thumb_first_only
        shift: [10, 11]
    screw_middle_top:
      $extends: points.zones.screw_outer_bottom
      anchor:
        ref: matrix_ring_top
        shift: [10, 10]
    screw_inner_bottom:
      $extends: points.zones.screw_outer_bottom
      anchor:
        ref: matrix_inner_bottom
        shift: [10, -11]
    screw_inner_top:
      $extends: points.zones.screw_outer_bottom
      anchor:
        ref: matrix_inner_num
        shift: [10, 6]
    matrix_mx:
      $extends: points.zones.matrix
      key:
        tags:
        - mx_key
        spread: mx_key_spread
        padding: mx_key_padding
        bind: [2, 2, 2, 2]
    thumb_mx:
      $extends: points.zones.thumb
      anchor:
        ref: matrix_mx_inner_bottom
      key:
        tags:
        - mx_key
        spread: mx_key_spread
      rows:
        only:
          padding: mx_key_padding
outlines:
  _keycap_outline:
  - what: rectangle
    where: [key]
    size: [keycap_w, keycap_h]
  _panel:
  - what: rectangle
    where: [key]
    bound: true
    size: [key_spread - 4, key_padding - 3]
  _rst_pwr_trrs_wall_cutout:
  - what: rectangle
    where:
      ref: matrix_inner_home
      shift: [35.4, 0.5]
    size: [4, 31]
  _mcu_usb_wall_cutout:
  - what: rectangle
    where:
      ref: matrix_inner_num
      shift: [24, 13.4]
    size: [10, 4]
  _wall_outer:
  - what: outline
    name: _panel
    expand: 2.4
    joints: 1
  _wall_inner:
  - what: outline
    name: _panel
    expand: 0.4
    joints: 1
  _panel_wall_full:
  - what: outline
    name: _wall_outer
  - -_wall_inner
  - -_rst_pwr_trrs_wall_cutout
  - -_mcu_usb_wall_cutout
  _panel_filleted:
  - what: outline
    name: _panel
    fillet: 0.4

  _screws:
  - what: circle
    where: [screw]
    radius: screw_hole_radius
  _screw_material:
  - what: circle
    where: [screw]
    radius: screw_material_radius
  _heat_insert_hole:
  - what: circle
    where: [screw]
    radius: heat_insert_hole_radius
  _switch_cutouts:
  - what: rectangle
    where: [key]
    size: [key_cutout_w, key_cutout_h]
  _switch_spacer_cutouts:
  - what: rectangle
    where: [key]
    size: [key_cutout_w + 0.8, key_cutout_h + 0.8]
  _rotary_mcu_cutout:
  - what: rectangle
    where:
      ref: matrix_inner_top
      shift: [24, -8]
    size: [22, 79]
  - what: polygon
    points:
    - ref: matrix_inner_bottom
      shift: [13, -9]
    - ref: matrix_inner_bottom
      shift: [19, -9]
    - ref: matrix_inner_bottom
      shift: [19, -16.3]
    - ref: thumb_inner_only
      shift: [-17.966, 12]

  screw_posts:
  - what: outline
    name: _screw_material
  - -_heat_insert_hole
  top_plate:
  - what: outline
    name: _panel
    fillet: 1
  - -_switch_cutouts
  - -_screws
  - -_rotary_mcu_cutout
  spacer_plate:
  - what: outline
    name: top_plate
  - -_screws
  - -_switch_spacer_cutouts
  panel_wall:
  - what: outline
    name: _panel_wall_full
    fillet: 0.4
  bottom_plate:
  - what: outline
    name: _wall_inner
    fillet: 1
  - -_screw_material

pcbs:
  boost58:
    # pcb thickness: 1.6mm
    outlines:
      main:
        outline: _panel_filleted
      keycap_outline_draw_front:
        outline: _keycap_outline
        layer: F.SilkS
      keycap_outline_draw_back:
        outline: _keycap_outline
        layer: B.SilkS
      top_plate_cutout_draw:
        outline: _rotary_mcu_cutout
        layer: Dwgs.User
      panel_wall:
        outline: panel_wall
        layer: Dwgs.User
    references: true
    template: kicad8
    footprints:
      mmount_screws:
        what: mounting_hole_npth
        where: [screw]
        params:
          designator: M3_
          hole_size: screw_hole_radius * 2
          hole_drill: screw_hole_radius * 2
      # promicro:
      #   what: promicro
      #   where:
      #     ref: matrix_inner_num
      #     shift: [22, -6]
      #     rotate: -90
      #   params:
      #     orientation: up
      sparkfun_promicro:
        what: sparkfun_promicro_qwiic_pinless
        where:
          ref: matrix_inner_num
          shift: [24, -6]
          rotate: -90
        params:
          reversible: true
      choc_hotswap:
        what: switch_choc_v1_v2
        where: [key]
        params:
          designator: SW
          # Row-To-Column diode orientation
          from: "{{row_net}}"
          to: "D{{column_net}}"
          include_keycap: true
          include_corner_marks: true
          include_plated_holes: true
          include_v1_stabilizer_nets: true
          include_v2_stabilizer_nets: true
          LEFTSTABV2: "LED{{led_row_next}}{{led_col_next}}"
          RIGHTSTABV2: "LED{{led_row}}{{led_col}}"
          LEFTSTABV1: VCC
          RIGHTSTABV1: GND
          reversible: true
          hotswap: true
        adjust:
          rotate: switch_rotation
      key_diodes:
        what: diode_tht_sod123
        where: [key]
        adjust:
          shift: [diode_pos_x, diode_pos_y]
          rotate: diode_rotation
        params:
          reversible: true
          include_tht: false
          # Row-To-Column diode orientation
          from: "D{{column_net}}"
          to: "{{column_net}}"
      per_key_leds:
        what: led_sk6812mini-e
        where: [key]
        adjust:
          shift: [0, 5]
        params:
          designator: "L"
          P2: "LED{{led_row_next}}{{led_col_next}}"
          P4: "LED{{led_row}}{{led_col}}"
          reversible: true
          include_keepout: true
          include_courtyard: true
          signal_trace_width: 0.2
          gnd_trace_width: 0.2
          vcc_trace_width: 0.2
          choc_v2_stab_pth_as_via: true
          via_size: 0.56
          via_drill: 0.3
      trrs:
        what: trrs
        where:
          ref: matrix_inner_home
          shift: [34, 8]
          rotate: -90
        params:
          A: VCC
          B: D0
          C: D1
          D: GND
          reverse: true
          symmetric: false
      reset:
        what: reset_switch_smd_side
        params:
          reversible: true
        where:
          ref: matrix_inner_bottom
          shift: [32.1, 8]
          rotate: -90
      power_switch:
        what: power_switch_smd_side
        params:
          reversible: true
        where:
          ref: matrix_inner_home
          shift: [32.4, -1]
          # rotate: 90
      encoder_top:
        what: rotary
        where:
          ref: matrix_inner_home
          shift: [23, -8]
          rotate: -90
        params:
          designator: Rotary
          from: D20
          to: D6
          A: D7
          B: D8
          C: GND
      underglow_0:
        what: led_WS2812B
        where:
          ref: thumb_first_only
          shift: [-10, 32]
          rotate: -90
        params:
          designator: U_
          din: LED01
          dout: LEDu01
          reversible: true
      underglow_1:
        what: led_WS2812B
        where:
          ref: thumb_first_only
          shift: [-10, 70]
          rotate: -90
        params:
          designator: U_
          din: LEDu01
          dout: LEDu02
          reversible: true
      underglow_2:
        what: led_WS2812B
        where:
          ref: thumb_second_only
          shift: [10, 32]
          rotate: -90
        params:
          designator: U_
          din: LEDu02
          dout: LEDu03
          reversible: true
      underglow_3:
        what: led_WS2812B
        where:
          ref: thumb_second_only
          shift: [10, 70]
          rotate: -90
        params:
          designator: U_
          din: LEDu03
          dout: LEDu04
          reversible: true
      underglow_4:
        what: led_WS2812B
        where:
          ref: matrix_inner_bottom
          shift: [10, 7]
          rotate: -90
        params:
          designator: U_
          din: LEDu04
          dout: LEDu05
          reversible: true
      underglow_5:
        what: led_WS2812B
        where:
          ref: matrix_inner_top
          shift: [10, 7]
          rotate: -90
        params:
          designator: U_
          din: LEDu05
          dout: LEDu06
